import type { LevelDef } from './types';

/** Gentle intro: short 4-tier pyramid, spiral climbs to the right, one of each simple obstacle. */
const MEADOW: LevelDef = {
  name: 'meadow',
  skin: 'meadow',
  rings: 4,
  terraceDepth: 3,
  tierHeight: 4,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 1, offset: 3 },
    { ring: 0, side: 3, offset: -4 },
    { ring: 1, side: 2, offset: -2 },
    { ring: 1, side: 3, offset: 2 },
    { ring: 2, side: 3, offset: 0 },
    { ring: 3, side: 0, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 0, offset: -3 },
    { ring: 2, side: 1, offset: -3 },
    { ring: 3, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: -9 },
  drum: { ring: 0, side: 0, offset: -12 },
  barrelSpawn: { ring: 3, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: 0 } },
    { type: 'gem', spot: { ring: 0, side: 0, offset: -5 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -6 } },
    { type: 'gem', spot: { ring: 1, side: 1, offset: 0 } },
    { type: 'hammer', spot: { ring: 1, side: 0, offset: 4 } },
    { type: 'oneup', spot: { ring: 2, side: 0, offset: -3 } },
    { type: 'gem', spot: { ring: 2, side: 3, offset: -4 } },
    { type: 'gem', spot: { ring: 3, side: 3, offset: 3 } },
    { type: 'hotdog', spot: { ring: 3, side: 2, offset: -2 } },
  ],
  patrols: [
    { ring: 1, from: [0, -6], to: [0, 6] },
    { ring: 2, from: [3, -5], to: [0, 5] },
    { ring: 0, from: [1, -8], to: [1, 1] },
    { ring: 3, from: [2, -3], to: [3, -2] },
  ],
  ghosts: 1,
  fires: 1,
  pits: [{ ring: 0, side: 0, offset: 0, width: 2 }],
  crumbles: [],
  conveyors: [{ ring: 1, side: 1, offset: 7, width: 4, dir: -1 }],
  platforms: [],
  locks: [{ kind: 'switch', ladder: 4, switchAt: { ring: 2, side: 1, offset: 3 } }],
};

/** 5 tiers, spiral climbs to the left; crumbling floors, a platform crossing and a key for the summit. */
const CANDY: LevelDef = {
  name: 'candy hills',
  skin: 'candy',
  rings: 5,
  terraceDepth: 3,
  tierHeight: 4,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 3, offset: 4 },
    { ring: 0, side: 1, offset: -6 },
    { ring: 1, side: 2, offset: 5 },
    { ring: 2, side: 1, offset: 0 },
    { ring: 2, side: 3, offset: 3 },
    { ring: 3, side: 0, offset: 2 },
    { ring: 4, side: 3, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 1, offset: 6 },
    { ring: 2, side: 0, offset: -4 },
    { ring: 3, side: 3, offset: -2 },
    { ring: 4, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: 9 },
  drum: { ring: 0, side: 0, offset: 14 },
  barrelSpawn: { ring: 4, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: -8.5 } },
    { type: 'gem', spot: { ring: 0, side: 3, offset: 12 } },
    { type: 'gem', spot: { ring: 1, side: 3, offset: -5 } },
    { type: 'hammer', spot: { ring: 1, side: 2, offset: 0 } },
    { type: 'hotdog', spot: { ring: 1, side: 2, offset: -8 } },
    { type: 'gem', spot: { ring: 2, side: 1, offset: 5 } },
    { type: 'oneup', spot: { ring: 2, side: 3, offset: -6 } },
    { type: 'key', spot: { ring: 3, side: 2, offset: -3 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: -3 } },
    { type: 'hotdog', spot: { ring: 3, side: 1, offset: 4 } },
    { type: 'gem', spot: { ring: 4, side: 0, offset: -2 } },
  ],
  patrols: [
    { ring: 1, from: [2, -10], to: [2, 10] },
    { ring: 3, from: [0, -6], to: [1, 6] },
    { ring: 0, from: [3, -12], to: [0, -12] },
    { ring: 2, from: [3, -8], to: [0, 8] },
    { ring: 4, from: [1, -3], to: [2, 3] },
  ],
  ghosts: 2,
  fires: 2,
  pits: [
    { ring: 1, side: 3, offset: -5, width: 2 },
    { ring: 3, side: 1, offset: -4, width: 2 },
  ],
  crumbles: [
    { ring: 0, side: 0, offset: -8.5, width: 3 },
    { ring: 1, side: 2, offset: 9.5, width: 3 },
  ],
  conveyors: [{ ring: 0, side: 3, offset: 10, width: 4, dir: -1 }],
  platforms: [{ ring: 2, side: 1, offset: 5, width: 6, platformWidth: 2, period: 4 }],
  locks: [{ kind: 'key', ladder: 6 }],
};

/** Tall 6-tier pyramid with short tiers; the route zig-zags direction every ring and uses everything. */
const DESERT: LevelDef = {
  name: 'desert arcade',
  skin: 'desert',
  rings: 6,
  terraceDepth: 3,
  tierHeight: 3,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 1, offset: -12 },
    { ring: 0, side: 3, offset: 8 },
    { ring: 1, side: 0, offset: 6 },
    { ring: 2, side: 1, offset: -2 },
    { ring: 3, side: 0, offset: 3 },
    { ring: 3, side: 2, offset: 0 },
    { ring: 4, side: 1, offset: 0 },
    { ring: 5, side: 0, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 2, offset: 5 },
    { ring: 2, side: 3, offset: -5 },
    { ring: 3, side: 2, offset: -6 },
    { ring: 4, side: 3, offset: 3 },
    { ring: 5, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: -12 },
  drum: { ring: 0, side: 0, offset: -17 },
  barrelSpawn: { ring: 5, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: -4 } },
    { type: 'gem', spot: { ring: 0, side: 0, offset: 14.5 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -16 } },
    { type: 'gem', spot: { ring: 1, side: 0, offset: 12 } },
    { type: 'hammer', spot: { ring: 2, side: 3, offset: 0 } },
    { type: 'gem', spot: { ring: 2, side: 1, offset: -8 } },
    { type: 'oneup', spot: { ring: 3, side: 2, offset: 4 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: 7.5 } },
    { type: 'key', spot: { ring: 4, side: 3, offset: 0 } },
    { type: 'hotdog', spot: { ring: 4, side: 0, offset: -5 } },
    { type: 'gem', spot: { ring: 5, side: 0, offset: -3 } },
  ],
  patrols: [
    { ring: 1, from: [0, -10], to: [0, 4] },
    { ring: 3, from: [3, -8], to: [0, -2] },
    { ring: 0, from: [1, -8], to: [1, 8] },
    { ring: 4, from: [2, -6], to: [3, 6] },
    { ring: 2, from: [2, -10], to: [3, -10] },
  ],
  ghosts: 2,
  fires: 3,
  pits: [
    { ring: 0, side: 0, offset: -4, width: 2 },
    { ring: 2, side: 0, offset: 10, width: 2 },
  ],
  crumbles: [
    { ring: 0, side: 0, offset: 14.5, width: 3 },
    { ring: 3, side: 1, offset: -6.5, width: 3 },
    { ring: 3, side: 0, offset: 7.5, width: 3 },
  ],
  conveyors: [
    { ring: 0, side: 0, offset: 6, width: 6, dir: 1 },
    { ring: 2, side: 1, offset: -8, width: 4, dir: -1 },
  ],
  platforms: [
    { ring: 1, side: 0, offset: 12, width: 6, platformWidth: 2, period: 3.6 },
    { ring: 4, side: 1, offset: -4, width: 4, platformWidth: 1.6, period: 3 },
  ],
  locks: [
    { kind: 'switch', ladder: 3, switchAt: { ring: 2, side: 0, offset: -6 } },
    { kind: 'key', ladder: 7 },
  ],
};

/** Played in order, then loop with rising speed. */
export const LEVELS: readonly LevelDef[] = [MEADOW, CANDY, DESERT];
