import type { LevelDef } from './types';

/** Gentle intro: short 4-tier pyramid, spiral climbs to the right, one of each simple obstacle. */
const MEADOW: LevelDef = {
  name: 'meadow',
  skin: 'meadow',
  rings: 4,
  terraceDepth: 3,
  tierHeight: 4,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 1, offset: 3 },
    { ring: 0, side: 3, offset: -4 },
    { ring: 1, side: 2, offset: -2 },
    { ring: 1, side: 3, offset: 2 },
    { ring: 2, side: 3, offset: 0 },
    { ring: 3, side: 0, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 0, offset: -3 },
    { ring: 2, side: 1, offset: -3 },
    { ring: 3, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: -9 },
  drum: { ring: 0, side: 0, offset: -12 },
  barrelSpawn: { ring: 3, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: 0 } },
    { type: 'gem', spot: { ring: 0, side: 0, offset: -5 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -6 } },
    { type: 'gem', spot: { ring: 1, side: 1, offset: 0 } },
    { type: 'hammer', spot: { ring: 1, side: 0, offset: 4 } },
    { type: 'oneup', spot: { ring: 2, side: 0, offset: -3 } },
    { type: 'gem', spot: { ring: 2, side: 3, offset: -4 } },
    { type: 'gem', spot: { ring: 3, side: 3, offset: 3 } },
    { type: 'hotdog', spot: { ring: 3, side: 2, offset: -2 } },
    { type: 'letter-1', spot: { ring: 0, side: 2, offset: 0 } },
    { type: 'letter-u', spot: { ring: 1, side: 3, offset: -7 } },
    { type: 'letter-p', spot: { ring: 3, side: 1, offset: -2 } },
  ],
  totems: [{ ring: 0, from: [0, 3], to: [0, 11] }],
  patrols: [
    { ring: 1, from: [0, -6], to: [0, 6] },
    { ring: 2, from: [3, -5], to: [0, 5] },
    { ring: 0, from: [1, -8], to: [1, 1] },
    { ring: 3, from: [2, -3], to: [3, -2] },
  ],
  ghosts: 1,
  fires: 1,
  pits: [{ ring: 0, side: 0, offset: 0, width: 2 }],
  crumbles: [],
  conveyors: [{ ring: 1, side: 1, offset: 7, width: 4, dir: -1 }],
  platforms: [],
  locks: [{ kind: 'switch', ladder: 4, switchAt: { ring: 2, side: 1, offset: 3 } }],
};

/** 5 tiers, spiral climbs to the left; crumbling floors, a platform crossing and a key for the summit. */
const CANDY: LevelDef = {
  name: 'candy hills',
  skin: 'candy',
  rings: 5,
  terraceDepth: 3,
  tierHeight: 4,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 3, offset: 4 },
    { ring: 0, side: 1, offset: -6 },
    { ring: 1, side: 2, offset: 5 },
    { ring: 2, side: 1, offset: 0 },
    { ring: 2, side: 3, offset: 3 },
    { ring: 3, side: 0, offset: 2 },
    { ring: 4, side: 3, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 1, offset: 6 },
    { ring: 2, side: 0, offset: -4 },
    { ring: 3, side: 3, offset: -2 },
    { ring: 4, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: 9 },
  drum: { ring: 0, side: 0, offset: 14 },
  barrelSpawn: { ring: 4, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: -8.5 } },
    { type: 'gem', spot: { ring: 0, side: 3, offset: 12 } },
    { type: 'gem', spot: { ring: 1, side: 3, offset: -5 } },
    { type: 'hammer', spot: { ring: 1, side: 2, offset: 0 } },
    { type: 'hotdog', spot: { ring: 1, side: 2, offset: -8 } },
    { type: 'letter-u', spot: { ring: 2, side: 1, offset: 5 } },
    { type: 'oneup', spot: { ring: 2, side: 3, offset: -6 } },
    { type: 'key', spot: { ring: 3, side: 2, offset: -3 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: -3 } },
    { type: 'hotdog', spot: { ring: 3, side: 1, offset: 4 } },
    { type: 'gem', spot: { ring: 4, side: 0, offset: -2 } },
    { type: 'letter-1', spot: { ring: 0, side: 3, offset: -6 } },
    { type: 'letter-p', spot: { ring: 4, side: 2, offset: -2 } },
  ],
  totems: [{ ring: 0, from: [0, -4], to: [0, 5] }],
  patrols: [
    { ring: 1, from: [2, -10], to: [2, 10] },
    { ring: 3, from: [0, -6], to: [1, 6] },
    { ring: 0, from: [3, -12], to: [0, -12] },
    { ring: 2, from: [3, -8], to: [0, 8] },
    { ring: 4, from: [1, -3], to: [2, 3] },
  ],
  ghosts: 2,
  fires: 2,
  pits: [
    { ring: 1, side: 3, offset: -5, width: 2 },
    { ring: 3, side: 1, offset: -4, width: 2 },
  ],
  crumbles: [
    { ring: 0, side: 0, offset: -8.5, width: 3 },
    { ring: 1, side: 2, offset: 9.5, width: 3 },
  ],
  conveyors: [{ ring: 0, side: 3, offset: 10, width: 4, dir: -1 }],
  platforms: [{ ring: 2, side: 1, offset: 5, width: 6, platformWidth: 2, period: 4 }],
  locks: [{ kind: 'key', ladder: 6 }],
};

/** Tall 6-tier pyramid with short tiers; the route zig-zags direction every ring and uses everything. */
const DESERT: LevelDef = {
  name: 'desert arcade',
  skin: 'desert',
  rings: 6,
  terraceDepth: 3,
  tierHeight: 3,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 1, offset: -12 },
    { ring: 0, side: 3, offset: 8 },
    { ring: 1, side: 0, offset: 6 },
    { ring: 2, side: 1, offset: -2 },
    { ring: 3, side: 0, offset: 3 },
    { ring: 3, side: 2, offset: 0 },
    { ring: 4, side: 1, offset: 0 },
    { ring: 5, side: 0, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 2, offset: 5 },
    { ring: 2, side: 3, offset: -5 },
    { ring: 3, side: 2, offset: -6 },
    { ring: 4, side: 3, offset: 3 },
    { ring: 5, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: -12 },
  drum: { ring: 0, side: 0, offset: -17 },
  barrelSpawn: { ring: 5, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: -4 } },
    { type: 'gem', spot: { ring: 0, side: 0, offset: 14.5 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -16 } },
    { type: 'gem', spot: { ring: 1, side: 0, offset: 12 } },
    { type: 'hammer', spot: { ring: 2, side: 3, offset: 0 } },
    { type: 'gem', spot: { ring: 2, side: 1, offset: -8 } },
    { type: 'oneup', spot: { ring: 3, side: 2, offset: 4 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: 7.5 } },
    { type: 'key', spot: { ring: 4, side: 3, offset: 0 } },
    { type: 'hotdog', spot: { ring: 4, side: 0, offset: -5 } },
    { type: 'gem', spot: { ring: 5, side: 0, offset: -3 } },
    { type: 'letter-1', spot: { ring: 0, side: 3, offset: 14 } },
    { type: 'letter-u', spot: { ring: 1, side: 1, offset: -4 } },
    { type: 'letter-p', spot: { ring: 4, side: 2, offset: -4 } },
  ],
  totems: [{ ring: 2, from: [0, -3], to: [0, 3] }],
  patrols: [
    { ring: 1, from: [0, -10], to: [0, 4] },
    { ring: 3, from: [3, -8], to: [0, -2] },
    { ring: 0, from: [1, -8], to: [1, 8] },
    { ring: 4, from: [2, -6], to: [3, 6] },
    { ring: 2, from: [2, -10], to: [3, -10] },
  ],
  ghosts: 2,
  fires: 3,
  pits: [
    { ring: 0, side: 0, offset: -4, width: 2 },
    { ring: 2, side: 0, offset: 10, width: 2 },
  ],
  crumbles: [
    { ring: 0, side: 0, offset: 14.5, width: 3 },
    { ring: 3, side: 1, offset: -6.5, width: 3 },
    { ring: 3, side: 0, offset: 7.5, width: 3 },
  ],
  conveyors: [
    { ring: 0, side: 0, offset: 6, width: 6, dir: 1 },
    { ring: 2, side: 1, offset: -8, width: 4, dir: -1 },
  ],
  platforms: [
    { ring: 1, side: 0, offset: 12, width: 6, platformWidth: 2, period: 3.6 },
    { ring: 4, side: 1, offset: -4, width: 4, platformWidth: 1.6, period: 3 },
  ],
  locks: [
    { kind: 'switch', ladder: 3, switchAt: { ring: 2, side: 0, offset: -6 } },
    { kind: 'key', ladder: 7 },
  ],
};

/** Autumn: spring pads launch you over wide pits, acorns drop from the branches, 3 pumpkins unseal the summit. */
const HARVEST: LevelDef = {
  name: 'harvest woods',
  skin: 'autumn',
  tip: 'springs clear wide pits · gather 3 pumpkins',
  rings: 5,
  terraceDepth: 3,
  tierHeight: 4,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 1, offset: -4 },
    { ring: 0, side: 3, offset: 6 },
    { ring: 1, side: 2, offset: 3 },
    { ring: 2, side: 3, offset: 2 },
    { ring: 2, side: 1, offset: 0 },
    { ring: 3, side: 0, offset: -2 },
    { ring: 4, side: 3, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 0, offset: -6 },
    { ring: 2, side: 0, offset: 0 },
    { ring: 3, side: 1, offset: 3 },
    { ring: 4, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: -11 },
  drum: { ring: 0, side: 0, offset: -15 },
  barrelSpawn: { ring: 4, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: -6 } },
    { type: 'relic', spot: { ring: 0, side: 0, offset: 11 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -12 } },
    { type: 'hammer', spot: { ring: 0, side: 2, offset: 0 } },
    { type: 'gem', spot: { ring: 1, side: 1, offset: -1 } },
    { type: 'relic', spot: { ring: 1, side: 1, offset: 6 } },
    { type: 'oneup', spot: { ring: 2, side: 2, offset: -5 } },
    { type: 'relic', spot: { ring: 2, side: 2, offset: 8 } },
    { type: 'gem', spot: { ring: 2, side: 3, offset: 0 } },
    { type: 'hotdog', spot: { ring: 3, side: 3, offset: 4 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: -5 } },
    { type: 'gem', spot: { ring: 4, side: 0, offset: -3 } },
    { type: 'letter-1', spot: { ring: 0, side: 3, offset: 12 } },
    { type: 'letter-u', spot: { ring: 2, side: 2, offset: -9 } },
    { type: 'letter-p', spot: { ring: 3, side: 2, offset: 3 } },
  ],
  totems: [{ ring: 0, from: [0, 10.5], to: [0, 15] }],
  patrols: [
    { ring: 1, from: [2, -10], to: [2, 10] },
    { ring: 3, from: [0, -6], to: [1, 6] },
    { ring: 2, from: [3, -8], to: [0, 8] },
    { ring: 0, from: [3, -12], to: [0, -12] },
  ],
  ghosts: 1,
  fires: 2,
  pits: [
    { ring: 0, side: 0, offset: 4.5, width: 5 },
    { ring: 1, side: 1, offset: 9, width: 2 },
    { ring: 2, side: 3, offset: -4.5, width: 5 },
  ],
  crumbles: [{ ring: 1, side: 2, offset: -6.5, width: 3 }],
  conveyors: [],
  platforms: [],
  locks: [{ kind: 'relics', ladder: 6 }],
  springs: [
    { ring: 0, side: 0, offset: 0.8 },
    { ring: 2, side: 3, offset: -7.8 },
  ],
  drops: [
    { ring: 1, side: 1, offset: 2 },
    { ring: 2, side: 2, offset: 6 },
    { ring: 3, side: 3, offset: 5 },
  ],
  crawlers: [
    { ring: 0, from: [1, -14], to: [1, -6] },
    { ring: 2, from: [2, 4], to: [2, 9] },
    { ring: 3, from: [3, 3], to: [0, -4] },
  ],
};

/** Winter: slippery ice before the pits, icicles, penguins that belly slide, and a switch plus key to reach the top. */
const FROST: LevelDef = {
  name: 'frost peak',
  skin: 'winter',
  tip: 'ice is slippery · icicles fall when you pass',
  rings: 5,
  terraceDepth: 3,
  tierHeight: 3,
  summitHalf: 4,
  ladders: [
    { ring: 0, side: 3, offset: 6 },
    { ring: 0, side: 1, offset: -5 },
    { ring: 1, side: 0, offset: -4 },
    { ring: 1, side: 2, offset: 5 },
    { ring: 2, side: 3, offset: 3 },
    { ring: 3, side: 0, offset: 2 },
    { ring: 4, side: 3, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 1, offset: 0 },
    { ring: 2, side: 2, offset: 0 },
    { ring: 3, side: 1, offset: 3 },
    { ring: 4, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: 8 },
  drum: { ring: 0, side: 0, offset: 14 },
  barrelSpawn: { ring: 4, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: 3 } },
    { type: 'gem', spot: { ring: 0, side: 0, offset: -13 } },
    { type: 'hotdog', spot: { ring: 0, side: 3, offset: 12 } },
    { type: 'hammer', spot: { ring: 0, side: 2, offset: 0 } },
    { type: 'gem', spot: { ring: 1, side: 0, offset: -10 } },
    { type: 'key', spot: { ring: 1, side: 3, offset: 12.5 } },
    { type: 'oneup', spot: { ring: 2, side: 1, offset: 5 } },
    { type: 'gem', spot: { ring: 2, side: 3, offset: 5 } },
    { type: 'hotdog', spot: { ring: 3, side: 3, offset: 6 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: -2 } },
    { type: 'gem', spot: { ring: 4, side: 3, offset: 3 } },
    { type: 'letter-1', spot: { ring: 0, side: 1, offset: -8 } },
    { type: 'letter-u', spot: { ring: 2, side: 0, offset: 4 } },
    { type: 'letter-p', spot: { ring: 4, side: 1, offset: -3 } },
  ],
  totems: [{ ring: 0, from: [0, 0], to: [0, 5] }],
  patrols: [
    { ring: 1, from: [0, -12], to: [0, 4] },
    { ring: 2, from: [3, -8], to: [3, 8] },
    { ring: 0, from: [1, -10], to: [1, 10] },
    { ring: 3, from: [1, -6], to: [2, 6] },
  ],
  ghosts: 1,
  fires: 2,
  pits: [
    { ring: 0, side: 0, offset: -9, width: 2 },
    { ring: 2, side: 3, offset: 8, width: 2 },
  ],
  crumbles: [{ ring: 1, side: 3, offset: 9.5, width: 3 }],
  conveyors: [],
  platforms: [],
  locks: [
    { kind: 'switch', ladder: 5, switchAt: { ring: 2, side: 3, offset: 10.5 } },
    { kind: 'key', ladder: 6 },
  ],
  ice: [
    { ring: 0, side: 0, offset: -4, width: 6 },
    { ring: 1, side: 0, offset: -9, width: 6 },
    { ring: 2, side: 0, offset: -8, width: 4 },
    { ring: 3, side: 0, offset: -3, width: 6 },
  ],
  drops: [
    { ring: 0, side: 3, offset: 10 },
    { ring: 1, side: 0, offset: 0 },
    { ring: 2, side: 0, offset: -8 },
    { ring: 3, side: 0, offset: -5 },
  ],
  crawlers: [
    { ring: 0, from: [3, 8], to: [3, 16] },
    { ring: 2, from: [0, -11], to: [0, -5] },
    { ring: 3, from: [0, -7], to: [0, 0] },
  ],
};

/** Desert tomb: snakes that rear up, fire traps on a timer, crumbling sand, and 3 golden idols to unseal the summit. */
const TOMB: LevelDef = {
  name: 'serpent tomb',
  skin: 'tomb',
  tip: 'snakes rear up · fire traps keep time · find 3 idols',
  rings: 6,
  terraceDepth: 3,
  tierHeight: 3,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 3, offset: 8 },
    { ring: 0, side: 1, offset: -6 },
    { ring: 1, side: 2, offset: 5 },
    { ring: 2, side: 1, offset: 2 },
    { ring: 2, side: 3, offset: 4 },
    { ring: 3, side: 0, offset: 3 },
    { ring: 4, side: 3, offset: 0 },
    { ring: 5, side: 2, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 0, offset: 0 },
    { ring: 2, side: 3, offset: -6 },
    { ring: 3, side: 2, offset: 3 },
    { ring: 4, side: 1, offset: 0 },
    { ring: 5, side: 0, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: 10 },
  drum: { ring: 0, side: 0, offset: 16 },
  barrelSpawn: { ring: 5, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: 0 } },
    { type: 'relic', spot: { ring: 0, side: 0, offset: -12 } },
    { type: 'gem', spot: { ring: 0, side: 3, offset: 16 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -12 } },
    { type: 'relic', spot: { ring: 1, side: 3, offset: -12 } },
    { type: 'gem', spot: { ring: 1, side: 2, offset: 15 } },
    { type: 'hammer', spot: { ring: 2, side: 0, offset: 0 } },
    { type: 'gem', spot: { ring: 2, side: 1, offset: 11 } },
    { type: 'hotdog', spot: { ring: 2, side: 2, offset: -10 } },
    { type: 'relic', spot: { ring: 3, side: 0, offset: 7 } },
    { type: 'gem', spot: { ring: 3, side: 1, offset: -9 } },
    { type: 'oneup', spot: { ring: 4, side: 1, offset: 3 } },
    { type: 'gem', spot: { ring: 4, side: 0, offset: -5 } },
    { type: 'letter-1', spot: { ring: 0, side: 1, offset: -15 } },
    { type: 'letter-u', spot: { ring: 2, side: 3, offset: -8 } },
    { type: 'letter-p', spot: { ring: 4, side: 1, offset: -3 } },
  ],
  patrols: [
    { ring: 1, from: [0, -10], to: [0, 4] },
    { ring: 3, from: [3, -8], to: [0, -2] },
    { ring: 0, from: [1, -8], to: [1, 8] },
    { ring: 4, from: [2, -6], to: [3, 6] },
    { ring: 2, from: [2, -10], to: [3, -10] },
  ],
  ghosts: 1,
  fires: 2,
  pits: [
    { ring: 0, side: 0, offset: -6, width: 2 },
    { ring: 2, side: 1, offset: 8, width: 2 },
  ],
  crumbles: [
    { ring: 0, side: 3, offset: 13.5, width: 3 },
    { ring: 3, side: 1, offset: -5.5, width: 3 },
  ],
  conveyors: [],
  platforms: [{ ring: 1, side: 2, offset: 11, width: 6, platformWidth: 2, period: 3.6 }],
  locks: [{ kind: 'relics', ladder: 7 }],
  jets: [
    { ring: 0, side: 0, offset: 4, period: 3 },
    { ring: 1, side: 3, offset: 1, period: 2.6 },
    { ring: 1, side: 3, offset: -9, period: 2.6, phase: 1.3 },
    { ring: 2, side: 2, offset: -6, period: 3.4 },
    { ring: 4, side: 3, offset: 4, period: 2.8 },
  ],
  drops: [
    { ring: 0, side: 3, offset: 11 },
    { ring: 2, side: 1, offset: 11 },
    { ring: 4, side: 0, offset: -4 },
  ],
  crawlers: [
    { ring: 0, from: [0, -18], to: [0, -8] },
    { ring: 1, from: [3, -8], to: [3, -2] },
    { ring: 2, from: [2, -12], to: [2, -2] },
    { ring: 3, from: [0, 4], to: [0, 9] },
    { ring: 4, from: [0, -6], to: [3, 6] },
  ],
};

/** Summer volcano: lava jets, falling lava rocks, scorpions, spring jumps, a switch gate and a key door. Uses everything. */
const VOLCANO: LevelDef = {
  name: 'volcano isle',
  skin: 'volcano',
  tip: 'lava jets erupt on a beat · ride the springs',
  rings: 6,
  terraceDepth: 3,
  tierHeight: 4,
  summitHalf: 3,
  ladders: [
    { ring: 0, side: 1, offset: -8 },
    { ring: 0, side: 3, offset: 5 },
    { ring: 1, side: 0, offset: 6 },
    { ring: 2, side: 1, offset: 0 },
    { ring: 2, side: 3, offset: -4 },
    { ring: 3, side: 0, offset: -3 },
    { ring: 4, side: 1, offset: -2 },
    { ring: 5, side: 0, offset: 0 },
  ],
  chutes: [
    { ring: 1, side: 2, offset: 0 },
    { ring: 2, side: 2, offset: 5 },
    { ring: 3, side: 2, offset: -4 },
    { ring: 4, side: 3, offset: 0 },
    { ring: 5, side: 2, offset: 0 },
  ],
  playerStart: { ring: 0, side: 0, offset: -10 },
  drum: { ring: 0, side: 0, offset: -16 },
  barrelSpawn: { ring: 5, side: 1, offset: 1 },
  items: [
    { type: 'gem', spot: { ring: 0, side: 0, offset: 0 } },
    { type: 'gem', spot: { ring: 0, side: 0, offset: 12 } },
    { type: 'hotdog', spot: { ring: 0, side: 1, offset: -15 } },
    { type: 'hammer', spot: { ring: 0, side: 3, offset: 0 } },
    { type: 'gem', spot: { ring: 1, side: 0, offset: 9 } },
    { type: 'hotdog', spot: { ring: 1, side: 1, offset: -14 } },
    { type: 'gem', spot: { ring: 2, side: 0, offset: 12 } },
    { type: 'oneup', spot: { ring: 2, side: 3, offset: 0 } },
    { type: 'gem', spot: { ring: 3, side: 0, offset: 0 } },
    { type: 'key', spot: { ring: 4, side: 0, offset: 5 } },
    { type: 'gem', spot: { ring: 4, side: 0, offset: -1 } },
    { type: 'hotdog', spot: { ring: 5, side: 0, offset: 3 } },
    { type: 'letter-1', spot: { ring: 0, side: 3, offset: 12 } },
    { type: 'letter-u', spot: { ring: 2, side: 0, offset: -4 } },
    { type: 'letter-p', spot: { ring: 4, side: 3, offset: -3 } },
  ],
  totems: [{ ring: 3, from: [1, -9], to: [1, -3] }],
  patrols: [
    { ring: 1, from: [1, -14], to: [1, -2] },
    { ring: 3, from: [0, -8], to: [0, 0] },
    { ring: 0, from: [1, -8], to: [2, 8] },
    { ring: 4, from: [2, -6], to: [3, 6] },
    { ring: 2, from: [2, -10], to: [3, -10] },
  ],
  ghosts: 2,
  fires: 3,
  pits: [
    { ring: 0, side: 0, offset: 8.5, width: 5 },
    { ring: 3, side: 0, offset: 4.5, width: 5 },
  ],
  crumbles: [{ ring: 1, side: 0, offset: 11.5, width: 3 }],
  conveyors: [
    { ring: 0, side: 0, offset: 15, width: 4, dir: 1 },
    { ring: 4, side: 1, offset: -5, width: 2, dir: -1 },
  ],
  platforms: [{ ring: 2, side: 1, offset: -7, width: 6, platformWidth: 2, period: 3.4 }],
  locks: [
    { kind: 'switch', ladder: 5, switchAt: { ring: 2, side: 0, offset: 10 } },
    { kind: 'key', ladder: 7 },
  ],
  springs: [
    { ring: 0, side: 0, offset: 4.8 },
    { ring: 3, side: 0, offset: 8.2 },
  ],
  jets: [
    { ring: 0, side: 0, offset: -3, period: 3.2 },
    { ring: 1, side: 1, offset: -12, period: 2.8 },
    { ring: 4, side: 0, offset: 3, period: 2.6 },
  ],
  drops: [
    { ring: 0, side: 1, offset: -14 },
    { ring: 1, side: 0, offset: 14 },
    { ring: 3, side: 1, offset: -6 },
  ],
  crawlers: [
    { ring: 1, from: [0, 7], to: [0, 15] },
    { ring: 2, from: [0, 7], to: [0, 12] },
    { ring: 4, from: [0, -6], to: [0, 6] },
  ],
};

/** Played in order, then loop with rising speed. */
export const LEVELS: readonly LevelDef[] = [MEADOW, CANDY, DESERT, HARVEST, FROST, TOMB, VOLCANO];
